#!/bin/bash

# Slackware build script for popcorntime

# Copyright 2025-2026 Vladislav 'fsLeg' Borisov, Moscow, Russia
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=popcorntime
TARNAM=popcorn-desktop
VERSION=${VERSION:-0.5.1}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i586" -o "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=$ARCH -mtune=i686"
  BITS="32"
  PLATFORM="ia32"
  NWVER="0.44.5"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  BITS="64"
  PLATFORM="x64"
  NWVER="0.86.0"
else
  echo "Only x86 and x86_64 architectures are supported."
  exit 1
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $TARNAM-$VERSION
tar xvf $CWD/$TARNAM-$VERSION.tar.gz --no-same-owner
cd $TARNAM-$VERSION
tar xfv $CWD/$PRGNAM-$VERSION-vendored-sources.tar --no-same-owner
mkdir -p cache/$NWVER-sdk
tar xf $CWD/nwjs-sdk-v$NWVER-linux-$PLATFORM.tar.gz --no-same-owner -C cache/$NWVER-sdk
find . ! -type l    -a \( \
  \(     -perm /111 -a ! -perm 755 -a -exec chmod -f 755 {} + \) -o \
  \(   ! -perm /111 -a ! -perm 644 -a -exec chmod -f 644 {} + \) \)
mv cache/$NWVER-sdk/nwjs-sdk-v$NWVER-linux-$PLATFORM cache/$NWVER-sdk/linux$BITS

# Fix libatomic.so copying
# https://aur.archlinux.org/cgit/aur.git/tree/copy-libatomic_fixes.patch?h=popcorntime
patch -p1 < $CWD/copy-libatomic_fixes.patch

# Use a proper nwjs version
sed -i "s|\(const defaultNwVersion = '\)[0-9.]\+|\1${NWVER}|" gulpfile.js

export YARN_YARN_OFFLINE_MIRROR="./vendor"
export YARN_CACHE_FOLDER="./cache"
export npm_config_cache="./cache"
export npm_config_nodedir="/usr"
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
yarn install \
  --ignore-engines \
  --frozen-lockfile \
  --offline

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
yarn build --no-update-notifier

find build/Popcorn-Time/linux$BITS -type f -perm -u+r -exec chmod a+r {} \;
find build/Popcorn-Time/linux$BITS -type f -perm -u+x -exec chmod a+x {} \;
find build/Popcorn-Time/linux$BITS -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs chmod a+x 2> /dev/null || true

mkdir -p $PKG/opt
cp -a build/Popcorn-Time/linux$BITS $PKG/opt/$PRGNAM

find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

mkdir -p $PKG/usr/share/applications
install -Dm644 dist/linux/appimage/Popcorn-Time.desktop $PKG/usr/share/applications/
for geometry in 16x16 24x24 32x32 48x48 64x64 96x96 128x128 256x256; do
  mkdir -p $PKG/usr/share/icons/hicolor/$geometry/apps
  magick dist/linux/appimage/Popcorn-Time.png -resize $geometry $PKG/usr/share/icons/hicolor/$geometry/apps/Popcorn-Time.png
done

mkdir -p $PKG/usr/bin
ln -s /opt/$PRGNAM/Popcorn-Time $PKG/usr/bin/

PKGDOC=$PKG/usr/doc/$PRGNAM-$VERSION
mkdir -p $PKGDOC
cp -a \
  build/Popcorn-Time/linux$BITS/{CHANGELOG.md,LICENSE.txt,README.md,credits.html} \
  $PKGDOC
cat $CWD/$PRGNAM.SlackBuild > $PKGDOC/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
